
server:
  port: 8089

spring:
  application:
    name: rest-template-practice

  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/rest_template_practice
    ## createDatabaseIfNotExist=true property only works for MySQL
    username: postgres
    password: root


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          batch_size: 50
        order_inserts: true

    hibernate:
      ddl-auto: create
    show-sql: true