#Application Port
server:
  port: 8089

#Setup TimeZone
user:
  timezone: BST

#Application Basic Details
spring:
  application:
    name: dhrubok-practice-service-one

#Database Configuration
#H2
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

# Observing Hibernate Performance
  jpa:
    properties:
      hibernate:
        generate_statistics: true

#Swaggger custom URL
springdoc:
  swagger-ui:
    path: /documentation

# Hibernate Errors wll be logged
logging:
  level:
    org:
      hibernate: INFO
