#Application Port
server:
  port: 8089

#Application Basic Details
spring:
  application:
    name: dhrubok-practice-service-one

#Database Configuration
#H2
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

#Swaggger custom URL
springdoc:
  swagger-ui:
    path: /documentation