server:
  port: 8089

spring:
  application:
    name: Jpa And Entity Manager Practice

  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
       # format_sql: true
logging:
  level:
    org:
      hibernate:
        #type: trace
